CREATE DATABASE ROMAN;
GO

USE ROMAN;
GO

CREATE TABLE professor(
idProfessor INT PRIMARY KEY IDENTITY(1,1),
nomeProfessor VARCHAR(60) NOT NULL UNIQUE,
);

CREATE TABLE tema(
idTema INT PRIMARY KEY IDENTITY(1,1),
nomeTema VARCHAR(30) NOT NULL UNIQUE,
);

CREATE TABLE projeto(
idProjeto INT PRIMARY KEY IDENTITY(1,1),
idTema INT FOREIGN KEY REFERENCES tema(idTema),
idProfessor INT FOREIGN KEY REFERENCES professor(idProfessor),
nomeProjeto VARCHAR(60) NOT NULL UNIQUE,
descricao VARCHAR(80) NOT NULL,
);